"""
First-run setup wizard for TwitchBot.

Modes:
- Full: ask for Twitch app credentials + channel + OBS (developer / first owner setup)
- Shared app: APP_ID / APP_SECRET already present → only ask for channel + OBS

Usage:
  python setup_wizard.py
  python setup_wizard.py --if-needed
  python setup_wizard.py --force
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    from config import BOT_ROOT
except Exception:
    BOT_ROOT = Path(__file__).resolve().parent

ENV_PATH = BOT_ROOT / ".env"
ENV_EXAMPLE = BOT_ROOT / ".env.example"


def _read_env_file(path: Path) -> dict:
    values = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        raw = line.strip()
        if not raw or raw.startswith("#") or "=" not in raw:
            continue
        key, _, value = raw.partition("=")
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def _has_app_credentials(values: dict | None = None) -> bool:
    values = values if values is not None else _read_env_file(ENV_PATH)
    return bool(values.get("APP_ID") and values.get("APP_SECRET"))


def setup_is_complete() -> bool:
    """Ready to run when app creds + target channel exist."""
    values = _read_env_file(ENV_PATH)
    return _has_app_credentials(values) and bool(values.get("TARGET_CHANNEL"))


def write_env(values: dict) -> None:
    existing = _read_env_file(ENV_PATH)
    existing.update({k: str(v) for k, v in values.items() if v is not None})

    order = [
        "APP_ID",
        "APP_SECRET",
        "TARGET_CHANNEL",
        "OBS_HOST",
        "OBS_PORT",
        "OBS_PASSWORD",
        "AUTO_CREATE_OBS_SOURCES",
        "HOSTED_AUDIO_API_KEY",
    ]
    lines = [
        "# Generated by setup_wizard.py — do not show this file on stream.",
        "# Re-run anytime: python setup_wizard.py",
        "",
    ]
    seen = set()
    for key in order:
        if key in existing:
            lines.append(f"{key}={existing[key]}")
            seen.add(key)
    for key, value in existing.items():
        if key not in seen:
            lines.append(f"{key}={value}")
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def test_obs_connection(host: str, port: str, password: str) -> tuple[bool, str]:
    try:
        from obswebsocket import obsws
    except ImportError:
        return False, "obs-websocket-py is not installed (pip install -r requirements.txt)"

    client = None
    try:
        client = obsws(host.strip() or "127.0.0.1", int(port or 4455), password or "")
        client.connect()
        return True, f"Connected to OBS at {host}:{port}"
    except Exception as error:
        return False, f"OBS connection failed: {error}"
    finally:
        if client is not None:
            try:
                client.disconnect()
            except Exception:
                pass


def run_wizard(force: bool = False) -> bool:
    """Show the GUI. Returns True if setup finished successfully."""
    if setup_is_complete() and not force:
        return True

    try:
        import tkinter as tk
        from tkinter import messagebox
    except Exception as error:
        print(f"⚠️ Tkinter unavailable ({error}). Create a .env manually from .env.example")
        return setup_is_complete()

    existing = _read_env_file(ENV_PATH)
    if not existing and ENV_EXAMPLE.exists():
        existing = _read_env_file(ENV_EXAMPLE)

    shared_app = _has_app_credentials(existing)
    result = {"saved": False}

    root = tk.Tk()
    root.title("TwitchBot Setup")
    root.attributes("-topmost", True)
    root.resizable(True, True)
    root.configure(bg="#12141c")
    root.minsize(520, 420)

    width, height = 560, 640 if not shared_app else 520
    root.update_idletasks()
    x = max((root.winfo_screenwidth() - width) // 2, 0)
    y = max((root.winfo_screenheight() - height) // 4, 0)
    root.geometry(f"{width}x{height}+{x}+{y}")

    # Layout: scrollable body + fixed footer so buttons never fall off-screen
    footer = tk.Frame(root, bg="#12141c", padx=22, pady=14)
    footer.pack(side="bottom", fill="x")

    body_wrap = tk.Frame(root, bg="#12141c")
    body_wrap.pack(side="top", fill="both", expand=True)

    canvas = tk.Canvas(body_wrap, bg="#12141c", highlightthickness=0)
    scrollbar = tk.Scrollbar(body_wrap, orient="vertical", command=canvas.yview)
    outer = tk.Frame(canvas, bg="#12141c", padx=22, pady=18)

    outer.bind(
        "<Configure>",
        lambda e: canvas.configure(scrollregion=canvas.bbox("all")),
    )
    canvas_window = canvas.create_window((0, 0), window=outer, anchor="nw")
    canvas.configure(yscrollcommand=scrollbar.set)

    def _on_canvas_configure(event):
        canvas.itemconfig(canvas_window, width=event.width)

    canvas.bind("<Configure>", _on_canvas_configure)
    canvas.pack(side="left", fill="both", expand=True)
    scrollbar.pack(side="right", fill="y")

    def _on_mousewheel(event):
        canvas.yview_scroll(int(-1 * (event.delta / 120)), "units")

    canvas.bind_all("<MouseWheel>", _on_mousewheel)

    pad = {"bg": "#12141c"}
    label_fg = "#c9d2e8"
    entry_bg = "#0f131d"
    entry_fg = "#ffffff"
    accent = "#4cd2ff"

    tk.Label(
        outer,
        text="TwitchBot Setup",
        font=("Segoe UI", 18, "bold"),
        fg="#f2f5ff",
        **pad,
    ).pack(anchor="w")

    if shared_app:
        subtitle = (
            "App credentials are already set. Just enter your channel and OBS details.\n"
            "Saved to .env — never show that file on stream."
        )
    else:
        subtitle = (
            "First-time owner setup: Twitch app + channel + OBS.\n"
            "Saved to .env — never show that file on stream."
        )
    tk.Label(
        outer,
        text=subtitle,
        font=("Segoe UI", 10),
        fg="#8b95ad",
        justify="left",
        **pad,
    ).pack(anchor="w", pady=(4, 14))

    fields = {}

    def add_field(parent, key, label, default="", show=None):
        tk.Label(parent, text=label, font=("Segoe UI", 9, "bold"), fg=label_fg, **pad).pack(anchor="w")
        var = tk.StringVar(value=str(default or ""))
        entry = tk.Entry(
            parent,
            textvariable=var,
            font=("Segoe UI", 11),
            bg=entry_bg,
            fg=entry_fg,
            insertbackground=entry_fg,
            relief="flat",
            show=show or "",
        )
        entry.pack(fill="x", ipady=7, pady=(3, 10))
        fields[key] = var
        return var

    # Owner-only fields when credentials are missing
    if not shared_app:
        add_field(outer, "APP_ID", "Twitch Client ID (APP_ID)", existing.get("APP_ID", ""))
        add_field(
            outer,
            "APP_SECRET",
            "Twitch Client Secret (APP_SECRET)",
            existing.get("APP_SECRET", ""),
            show="*",
        )
    else:
        # Keep values for write_env without showing them
        fields["APP_ID"] = tk.StringVar(value=existing.get("APP_ID", ""))
        fields["APP_SECRET"] = tk.StringVar(value=existing.get("APP_SECRET", ""))
        tk.Label(
            outer,
            text="✓ Twitch app credentials loaded (hidden)",
            font=("Segoe UI", 10, "bold"),
            fg="#5ddea6",
            **pad,
        ).pack(anchor="w", pady=(0, 12))

    add_field(
        outer,
        "TARGET_CHANNEL",
        "Your Twitch channel login (lowercase, no #)",
        existing.get("TARGET_CHANNEL", ""),
    )
    add_field(outer, "OBS_HOST", "OBS WebSocket host", existing.get("OBS_HOST", "127.0.0.1"))
    add_field(outer, "OBS_PORT", "OBS WebSocket port", existing.get("OBS_PORT", "4455"))
    add_field(
        outer,
        "OBS_PASSWORD",
        "OBS WebSocket password",
        existing.get("OBS_PASSWORD", ""),
        show="*",
    )

    auto_default = str(existing.get("AUTO_CREATE_OBS_SOURCES", "true")).lower() in {
        "1",
        "true",
        "yes",
        "on",
        "",
    }
    auto_var = tk.BooleanVar(value=auto_default)
    tk.Checkbutton(
        outer,
        text="Auto-create OBS browser sources (Bot, BotText, RewardOverlay)",
        variable=auto_var,
        onvalue=True,
        offvalue=False,
        bg="#12141c",
        fg="#e8ecf8",
        activebackground="#12141c",
        activeforeground="#e8ecf8",
        selectcolor="#1a1f2b",
        font=("Segoe UI", 10),
        anchor="w",
    ).pack(fill="x", pady=(4, 8))

    status = tk.Label(
        footer,
        text="Tip: scroll if needed. Buttons stay at the bottom.",
        font=("Segoe UI", 9),
        fg="#8b95ad",
        bg="#12141c",
        wraplength=500,
        justify="left",
    )
    status.pack(anchor="w", pady=(0, 10))

    buttons = tk.Frame(footer, bg="#12141c")
    buttons.pack(fill="x")

    def style_btn(btn, bg, fg="#02131a"):
        btn.configure(
            bg=bg,
            fg=fg,
            activebackground=bg,
            activeforeground=fg,
            relief="flat",
            bd=0,
            padx=14,
            pady=8,
            cursor="hand2",
            font=("Segoe UI", 10, "bold"),
        )

    def collect():
        data = {key: var.get().strip() for key, var in fields.items()}
        data["AUTO_CREATE_OBS_SOURCES"] = "true" if auto_var.get() else "false"
        data["TARGET_CHANNEL"] = data.get("TARGET_CHANNEL", "").lstrip("#").lower()
        return data

    def on_test():
        data = collect()
        ok, message = test_obs_connection(data["OBS_HOST"], data["OBS_PORT"], data["OBS_PASSWORD"])
        status.configure(text=message, fg="#5ddea6" if ok else "#ff7b7b")

    def on_save():
        data = collect()
        required = ["APP_ID", "APP_SECRET", "TARGET_CHANNEL"]
        missing = [k for k in required if not data.get(k)]
        if missing:
            messagebox.showerror("Missing fields", "Please fill: " + ", ".join(missing))
            return
        write_env(data)
        result["saved"] = True
        status.configure(text=f"Saved {ENV_PATH.name}. You can close this and start the bot.", fg="#5ddea6")
        root.after(300, root.destroy)

    test_btn = tk.Button(buttons, text="Test OBS connection", command=on_test)
    style_btn(test_btn, "#9eb0d5")
    test_btn.pack(side="left")

    save_btn = tk.Button(buttons, text="Save & continue", command=on_save)
    style_btn(save_btn, accent)
    save_btn.pack(side="right")

    def on_close():
        try:
            canvas.unbind_all("<MouseWheel>")
        except Exception:
            pass
        root.destroy()

    root.protocol("WM_DELETE_WINDOW", on_close)
    root.lift()
    root.focus_force()
    root.mainloop()
    return result["saved"] or setup_is_complete()


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    force = "--force" in argv
    if_needed = "--if-needed" in argv

    if if_needed and setup_is_complete() and not force:
        print("✅ Setup already complete (.env found)")
        return 0

    ok = run_wizard(force=force or not if_needed)
    if not ok:
        print("❌ Setup was cancelled or incomplete.")
        return 1
    print("✅ Setup saved to .env")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
